# Generated by Django 5.1.5 on 2025-08-19 10:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, help_text='인기 검색어 문자열', max_length=255, unique=True)),
                ('search_count', models.IntegerField(default=1, help_text='해당 검색어의 총 검색 횟수')),
                ('last_searched', models.DateTimeField(default=django.utils.timezone.now, help_text='마지막으로 검색된 시간')),
            ],
            options={
                'verbose_name': '인기 검색어',
                'verbose_name_plural': '인기 검색어',
                'ordering': ['-search_count', '-last_searched'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, help_text='검색을 수행한 사용자 ID (인증된 사용자)', null=True)),
                ('query', models.CharField(db_index=True, help_text='사용자가 검색한 쿼리 문자열', max_length=255)),
                ('results_count', models.IntegerField(default=0, help_text='해당 검색 쿼리로 반환된 결과 수')),
                ('clicked_result_id', models.CharField(blank=True, help_text='검색 결과 중 사용자가 클릭한 게시물의 ID', max_length=50, null=True)),
                ('search_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='검색이 수행된 시간')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='검색 응답 시간 (밀리초)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='검색을 수행한 사용자의 IP 주소', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='검색을 수행한 사용자의 User-Agent 문자열', null=True)),
            ],
            options={
                'verbose_name': '검색 로그',
                'verbose_name_plural': '검색 로그',
                'ordering': ['-search_time'],
            },
        ),
    ]
